WIP: Reimplementation: Replace --with{in,out} with delegation to datediff
To support all --newer|--older|-lt|-le|-eq|-ne|-ge|-gt|--within|-w|--outside|-W comparison options.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/executionMarker b/bin/executionMarker
--- a/bin/executionMarker
+++ b/bin/executionMarker
@@ -21,15 +21,16 @@ shopt -qs extglob
 
 printShortUsage()
 {
+    local comparisonArgs="$(datediff --get-short-usage comparisons)"
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: %q %s\n' "$(basename "$1")" '[--basedir DIR|--base-type config|data|runtime|cache|temp] [-n|--namespace NAMESPACE] -g|--group GROUP [-?|-h|--help]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... (--start-read-transaction OWNER-ID [--transaction-timeout TX-TIMEOUT]|--start-write-transaction OWNER-ID [--transaction-timeout TX-TIMEOUT]|--upgrade-to-write-transaction OWNER-ID [--transaction-timeout TX-TIMEOUT]|--end-transaction OWNER-ID|--abort-write-transaction OWNER-ID) [--timeout SECONDS] [--silence-transaction-errors]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... [(-x|--transactional [--transaction-timeout TX-TIMEOUT]|--within-transaction OWNER-ID|-X|--no-transaction) [--timeout SECONDS] [--silence-transaction-errors]] ...'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -u|--update SUBJECT [-C|--keep-context|-c|--context CONTEXT|-|--increment-context] [-T|--timestamp EPOCH] [-w|--within|-W|--without ...] [-x|--get-context] [--get-timestamp] [--get-time --format DATE-FORMAT|""] [--get-diff ...%S|%s|%[P]r|%[P]R|%[P]P|%[P]p...]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "    ... -u|--update SUBJECT [-C|--keep-context|-c|--context CONTEXT|-|--increment-context] [-T|--timestamp EPOCH] [${comparisonArgs}] [-x|--get-context] [--get-timestamp] [--get-time --format DATE-FORMAT|\"\"] [--get-diff ...%S|%s|%[P]r|%[P]R|%[P]P|%[P]p...]"
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -d|--diff SUBJECT [--format ...%S|%s|%[P]r|%[P]R|%[P]P|%[P]p...] [-f|--fallback-subject FALLBACK-SUBJECT]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -t|--time SUBJECT [--format DATE-FORMAT|""] [-f|--fallback-subject FALLBACK-SUBJECT]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -q|--query SUBJECT [-w|--within|-W|--without VALID-TIMESPAN[SUFFIX]|second|minute|hour|day|week|month|year|every N (seconds|minutes|hours|days|weeks)] [-x|--get-context] [--get-timestamp] [--get-time --format DATE-FORMAT|""] [--get-diff ...%S|%s|%[P]r|%[P]R|%[P]P|%[P]p...] [-f|--fallback-subject FALLBACK-SUBJECT [-F|--fallback-on-time]]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "    ... -q|--query SUBJECT [${comparisonArgs}] [-x|--get-context] [--get-timestamp] [--get-time --format DATE-FORMAT|\"\"] [--get-diff ...%S|%s|%[P]r|%[P]R|%[P]P|%[P]p...] [-f|--fallback-subject FALLBACK-SUBJECT [-F|--fallback-on-time]]"
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -D|--delete SUBJECT'
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... --drop'
 }
@@ -92,29 +93,11 @@ HELPDESCRIPTION
 				a Unix epoch, format this as DATE-FORMAT. If
 				empty, uses the default date format.
     --query|-q SUBJECT		Query whether a record for SUBJECT exists.
-    --within|-w VALID-TIMESPAN|TIMESLOT
-				Checks whether the time difference between the
-				last execution of SUBJECT and now is smaller or
-				equal to VALID-TIMESPAN / falls inside TIMESLOT.
-				Returns 1 if it is larger / outside the slot or
-				4 if no record for SUBJECT exists.
-				TIMESPAN is NUMBER[SUFFIX], where SUFFIX may be
-				's' for seconds (the default), 'm' for minutes,
-				'h' for hours or 'd' for days.
-				TIMESLOT can be one of
-				second|minute|hour|day|week|month|year, or
-				every N seconds|minutes|hours|days|weeks, which
-				doesn't translate to a fixed minimal timespan,
-				but instead ensures that this happens at least
-				once in the slot. For example, 'day' could mean
-				two executions within seconds, if the first
-				check happens before midnight and the next
-				shortly after midnight.
-    --without|-W VALID-TIMESPAN|TIMESLOT
-				Checks whether the time difference between the
-				last execution of SUBJECT and now is larger or
-				equal to VALID-TIMESPAN / falls outside
-				TIMESLOT.
+				The (typically negative) time difference between
+				the last execution of SUBJECT and now can be
+				compared through datediff options.
+				Returns 1 if that comparison fails or 4 if no
+				record for SUBJECT exists.
     --get-context|-x		Prints the recorded CONTEXT for SUBJECT (if it
 				exists).
     --get-timestamp		Prints the recorded timestamp (Unix epoch) for
@@ -135,8 +118,7 @@ HELPDESCRIPTION
 				hasn't been recorded.
     --fallback-on-time|-F	Also try FALLBACK-SUBJECT for the time
 				comparison if the time difference between the
-				last execution of SUBJECT and now does not fall
-				into the range given my --within or --without.
+				last execution of SUBJECT and now fails.
 				In other words, the fallback is also used if the
 				last execution of SUBJECT is too long ago or too
 				recent, not just when SUBJECT doesn't exist.
@@ -216,8 +198,8 @@ EXIT STATUS:
     2	Bad invocation, wrong or missing command-line arguments.
     3	Internal error or failed assertion.
     4	The queried SUBJECT (nor FALLBACK-SUBJECT if given) for --query, --diff,
-	--time, --within, --without / to-be-deleted SUBJECT for --delete does
-	not exist.
+	--time / time comparisons / to-be-deleted SUBJECT for --delete does not
+	exist.
     5	Time out while waiting to start a transaction.
     6	The current transaction has taken too long (TX-TIMEOUT). On
 	modifications --within-transaction, aborts. On --end-transaction, if it
@@ -225,36 +207,6 @@ EXIT STATUS:
 HELPTEXT
 }
 
-getSpan()
-{
-    local divider="$1"; shift
-    divider="${divider#every }"
-    divider="${divider% +([a-z])}"
-    printf '%d' "$divider"
-}
-parseTime()
-{
-    case "$1" in
-	+([0-9])?(s))		    timespan="${1%s}";;
-	+([0-9])m)		    timespan=$((${1%m} * 60));;
-	+([0-9])h)		    timespan=$((${1%h} * 3600));;
-	+([0-9])d)		    timespan=$((${1%d} * 86400));;
-	+([0-9])w)		    timespan=$((${1%d} * 604800));;
-	second)			    timeformat='%s';;
-	minute)			    timeformat='%F_%H:%M';;
-	hour)			    timeformat='%F_%H';;
-	day)			    timeformat='%F';;
-	week)			    timeformat='%G_%V';;
-	month)			    timeformat='%Y_%m';;
-	year)			    timeformat='%Y';;
-	every\ +([0-9])\ seconds)   timespan="$(getSpan "$1")"; timedivider=1;;
-	every\ +([0-9])\ minutes)   timespan="$(getSpan "$1")"; timedivider=60;;
-	every\ +([0-9])\ hours)	    timespan="$(getSpan "$1")"; timedivider=3600;;
-	every\ +([0-9])\ days)	    timespan="$(getSpan "$1")"; timedivider=86400;;
-	every\ +([0-9])\ weeks)	    timespan="$(getSpan "$1")"; timedivider=604800;;
-	*)			    printf >&2 'ERROR: Invalid TIMESPAN/TIMESLOT: "%s".\n' "$1"; printUsage "$0" >&2; exit 2;;
-    esac
-}
 multipleActionsError()
 {
     echo >&2 "ERROR: Only one of --update, --diff, --time, --query, --delete, --drop, --start-read-transaction, --start-write-transaction, --upgrade-to-write-transaction, --within-transaction, --end-transaction, --abort-write-transaction allowed."
@@ -283,13 +235,9 @@ isIncrementContext=
 isKeepContext=
 action=
 additionalInformation=()
-timespan=
-timeformat=
-timedivider=
 unset dateFormat
 diffFormat=
-spanCompareOp=
-formatCompareOp=
+typeset -a datediffArgs=()
 markerErrorStatusOverride=
 while [ $# -ne 0 ]
 do
@@ -325,8 +273,8 @@ do
 	--get-diff)		shift; additionalInformation+=(printTimeDiff); diffFormat="$1"; shift;;
 	--fallback-subject|-f)	shift; fallbackSubject="$1"; shift;;
 	--fallback-on-time|-F)	shift; isFallbackOnTime=t;;
-	--within|-w)	shift; parseTime "$1"; spanCompareOp='-ge'; formatCompareOp='='; additionalInformation+=(printTimeRange); markerErrorStatusOverride=4; shift;;
-	--without|-W)	shift; parseTime "$1"; spanCompareOp='-le'; formatCompareOp='!='; additionalInformation+=(printTimeRange); markerErrorStatusOverride=4; shift;;
+	--newer|--older|-lt|-le|-eq|-ne|-ge|-gt|--within|-w|--outside|-W)
+			datediffArgs+=("$1" "${2:?}"); shift; shift; additionalInformation+=(printTimeRange); markerErrorStatusOverride=4;;
 	--update|-u)	shift; [ "$action" ] && multipleActionsError "$0"; action='update'; subject="$1"; shift;;
 	--diff|-d)	shift; [ "$action" ] && multipleActionsError "$0"; action='timediff'; subject="$1"; shift;;
 	--time|-t)	shift; [ "$action" ] && multipleActionsError "$0"; action='lasttime'; subject="$1"; shift;;
@@ -334,7 +282,17 @@ do
 	--delete|-D)	shift; [ "$action" ] && multipleActionsError "$0"; action='delete'; subject="$1"; shift;;
 	--drop)		shift; [ "$action" ] && multipleActionsError "$0"; action='drop'; shift;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	-*)		if argCount=$(datediff --understands "$@"); then
+			    while ((argCount-- > 0))
+			    do
+				datediffArgs+=("$1"); shift
+			    done
+			elif [ $? -eq 2 ]; then
+			    exit 2
+			else
+			    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2
+			fi
+			;;
 	*)		break;;
     esac
 done
@@ -353,11 +311,11 @@ if [ $# -gt 0 ]; then
     printUsage "$0" >&2
     exit 2
 fi
-if [ -n "$timespan" -o -n "$timeformat" -o -n "$timedivider" ]; then
+if [ ${#datediffArgs[@]} -gt 0 ]; then
     if [ "$action" = 'query' ]; then
 	action="timerange${isFallbackOnTime:+${fallbackSubject:+WithTimeFallback}}"
     elif [ "$action" != 'update' ]; then
-	echo "ERROR: --within and --without can only be combined with --query or --update."
+	echo "ERROR: Time comparisons can only be combined with --query or --update."
 	echo
 	printUsage "$0"
 	exit 2
@@ -436,7 +394,7 @@ update()
 	local line; line="$(updateHandlingQuery --columns \*)" || return $?
 	parseMarker "$line" || return 0	# Empty record means new record here and is not a failure.
 	printAdditionalInformation
-	if [ -n "$timeformat" -o -n "$timedivider" -o -n "$spanCompareOp" ]; then
+	if [ ${#datediffArgs[@]} -gt 0 ]; then
 	    calculateTimeRange
 	fi
     fi
@@ -595,25 +553,13 @@ createView()
 
 calculateTimeRange()
 {
-    if [ -n "$timeformat" ]; then
-	local thisRun lastRun
-	thisRun="$(date --date "@$NOW" "+$timeformat")" || exit 3
-	lastRun="$(date --date "@$markerTimestamp" "+$timeformat")" || exit 3
-	[ "$lastRun" $formatCompareOp "$thisRun" ]
-    elif [ -n "$timedivider" ]; then
-	local thisDivision lastDivision
-	thisDivision="$((NOW / timedivider))"
-	lastDivision="$((markerTimestamp / timedivider))"
-	[ $timespan $spanCompareOp $((thisDivision - lastDivision)) ]
-    else
-	[ $markerTimestamp $spanCompareOp $((NOW - timespan)) ]
-    fi
+    datediff "${datediffArgs[@]}" "@$markerTimestamp"
 }
 
 printTimeRange()
 {
     # This function just serves as a marker in additionalInformation; it does
-    # nothing because for --within/--without, no information is printed, but the
+    # nothing because for time comparisons, no information is printed, but the
     # result is in the exit status (and therefore calculateTimeRange() has to
     # run last).
     :
