ENH: Allow combination of --update with --get-{context,timestamp} and --with{in,out}
This is easy to implement, as the underlying miniDB now supports this and we just need to tack on the --columns * parameter and capture the output. Processing of the returned record is then delegated to the (now extracted) functionality from --query / --within / --without: parseMarker() followed by printAdditionalInformation() and calculateTimeRange().
This may help clients avoid a second query call, especially in combination with the new --increment-context feature.

diff --git a/bin/executionMarker b/bin/executionMarker
--- a/bin/executionMarker
+++ b/bin/executionMarker
@@ -24,7 +24,7 @@ printShortUsage()
     printf 'Usage: %q %s\n' "$(basename "$1")" '[--basedir DIR|--base-type config|data|runtime|cache] [-n|--namespace NAMESPACE] -g|--group GROUP [-?|-h|--help]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... (--start-read-transaction OWNER-ID [--transaction-timeout TX-TIMEOUT]|--start-write-transaction OWNER-ID [--transaction-timeout TX-TIMEOUT]|--upgrade-to-write-transaction OWNER-ID [--transaction-timeout TX-TIMEOUT]|--end-transaction OWNER-ID|--abort-write-transaction OWNER-ID) [--timeout SECONDS] [--silence-transaction-errors]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '... [(-t|--transactional [--transaction-timeout TX-TIMEOUT]|--within-transaction|-T|--no-transaction) [--timeout SECONDS] [--silence-transaction-errors]] ...'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -u|--update SUBJECT [-C|--keep-context|-c|--context CONTEXT|-|--increment-context] [-t|--timestamp EPOCH]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -u|--update SUBJECT [-C|--keep-context|-c|--context CONTEXT|-|--increment-context] [-t|--timestamp EPOCH] [-w|--within|-W|--without ...] [-x|--get-context] [--get-timestamp]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -d|--diff SUBJECT [-f|--fallback-subject FALLBACK-SUBJECT]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -t|--time SUBJECT [--format DATE-FORMAT|""] [-f|--fallback-subject FALLBACK-SUBJECT]'
     printf 'Usage: %q %s\n' "$(basename "$1")" '    ... -q|--query SUBJECT [-w|--within|-W|--without VALID-TIMESPAN[SUFFIX]|second|minute|hour|day|week|month|year|every N (seconds|minutes|hours|days|weeks)] [-x|--get-context] [--get-timestamp] [-f|--fallback-subject FALLBACK-SUBJECT]'
@@ -259,6 +259,7 @@ timedivider=
 unset dateFormat
 spanCompareOp=
 formatCompareOp=
+isUpdateQuery=
 while [ $# -ne 0 ]
 do
     case "$1" in
@@ -287,11 +288,11 @@ do
 	--keep-context|-C)	shift; isKeepContext=t;;
 	--timestamp|-t)		shift; now="$1"; shift;;
 	--format)		shift; dateFormat="$1"; shift;;
-	--get-context|-x)	shift; isGetContext=t;;
-	--get-timestamp)	shift; isGetTimestamp=t;;
+	--get-context|-x)	shift; isGetContext=t; isUpdateQuery=t;;
+	--get-timestamp)	shift; isGetTimestamp=t; isUpdateQuery=t;;
 	--fallback-subject|-f)	shift; fallbackSubject="$1"; shift;;
-	--within|-w)	shift; parseTime "$1"; spanCompareOp='-ge'; formatCompareOp='='; shift;;
-	--without|-W)	shift; parseTime "$1"; spanCompareOp='-le'; formatCompareOp='!='; shift;;
+	--within|-w)	shift; parseTime "$1"; spanCompareOp='-ge'; formatCompareOp='='; isUpdateQuery=t; shift;;
+	--without|-W)	shift; parseTime "$1"; spanCompareOp='-le'; formatCompareOp='!='; isUpdateQuery=t; shift;;
 	--update|-u)	shift; [ "$action" ] && multipleActionsError "$0"; action='update'; subject="$1"; shift;;
 	--diff|-d)	shift; [ "$action" ] && multipleActionsError "$0"; action='timediff'; subject="$1"; shift;;
 	--time|-t)	shift; [ "$action" ] && multipleActionsError "$0"; action='lasttime'; subject="$1"; shift;;
@@ -321,8 +322,8 @@ fi
 if [ -n "$timespan" -o -n "$timeformat" -o -n "$timedivider" ]; then
     if [ "$action" = 'query' ]; then
 	action='timerange'
-    else
-	echo "ERROR: --within and --without can only be combined with --query"
+    elif [ "$action" != 'update' ]; then
+	echo "ERROR: --within and --without can only be combined with --query or --update."
 	echo
 	printUsage "$0"
 	exit 2
@@ -368,15 +369,29 @@ printAdditionalInformation()
 }
 
 
-update()
+updateHandlingQuery()
 {
     if [ "$isKeepContext" ]; then
-	database --update "$subject" --column "TIMESTAMP=$now"
+	database --update "$subject" --column "TIMESTAMP=$now" "$@"
     elif [ "$isIncrementContext" ]; then
-	database --update "$subject" --column "TIMESTAMP=$now" --column CONTEXT++
+	database --update "$subject" --column "TIMESTAMP=$now" --column CONTEXT++ "$@"
     else
 	# Cannot use --update "$subject --column "TIMESTAMP=$now" --column "CONTEXT=$context" because the context may consist of multiple, tab-separated columns, and only the --update RECORD supports that.
-	database --update "$subject	$now	$context"
+	database --update "$subject	$now	$context" "$@"
+    fi
+}
+
+update()
+{
+    if [ "$isUpdateQuery" ]; then
+	local line; line="$(updateHandlingQuery --columns \*)" || return $?
+	parseMarker "$line" || return 0	# Empty record means new record here and is not a failure.
+	printAdditionalInformation
+	if [ -n "$timeformat" -o -n "$timedivider" -o -n "$spanCompareOp" ]; then
+	    calculateTimeRange
+	fi
+    else
+	updateHandlingQuery
     fi
 }
 
